services:
    payment-service:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3002:3002'
        environment:
            MONGODB_URI: ${MONGODB_URI}
            ORDER_SERVICE_API: http://order-service:3001
            MERCADO_PAGO_API: ${MERCADO_PAGO_API}
            MERCADO_PAGO_CLIENT_SECRET: ${MERCADO_PAGO_CLIENT_SECRET}
            MERCADO_PAGO_CLIENT_ID: ${MERCADO_PAGO_CLIENT_ID}
            MERCADO_PAGO_QR_CODE_API: ${MERCADO_PAGO_QR_CODE_API}
            MERCADO_PAGO_WEBHOOK: ${MERCADO_PAGO_WEBHOOK}
        depends_on:
            - mongo
        volumes:
            - ./src:/app/src
        networks:
            - fast-food-network

    mongo:
        image: mongo:latest
        command:
            - '--logpath'
            - '/var/log/mongodb/mongod.log'
        volumes:
            - mongo_data:/data/db
        networks:
            - fast-food-network

volumes:
    mongo_data:

networks:
    fast-food-network:
