apiVersion: v1
kind: Service
metadata:
    name: fast-food-payment-service
spec:
    selector:
        app: fast-food-payment-service
    ports:
        - protocol: TCP
          port: 80 # TO-DO check
          targetPort: 3000
    type: ClusterIP # TO-DO check
