apiVersion: v1
kind: Service
metadata:
    name: payment-service
spec:
    selector:
        app: fast-food-payment
    ports:
        - protocol: TCP
          port: 3002
          targetPort: 3002
          nodePort: 32002
    type: NodePort