name: Fast-Food-Payment CI/CD

on:
    push:
        branches:
            - main

jobs:
    build-test:
        name: Build, Test and Validate
        runs-on: ubuntu-latest

        services:
            mongo:
                image: mongo:6
                ports:
                    - 27017:27017
                options: >-
                    --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" 
                    --health-interval=10s 
                    --health-timeout=5s 
                    --health-retries=5

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install root dependencies
              run: npm install

            - name: Run lint
              run: npm run lint

            - name: Run tests
              run: npm test
